# Gush configuration file, any comments will be lost.
adapter: github
issue_tracker: github
table-pr:
    fixed_tickets: ['Fixed Tickets', '']
    license: [License, MIT]
base: master
meta-header: "This file is part of Testing Sandbox package.\n\n(c) 1980-2015 Doctor Who <who@bb.co.uk>\n\nThis source file is subject to the MIT license that is bundled\nwith this source code in the file LICENSE."
repo_adapter: github
repo_org: sstok
repo_name: gush-experiments-sandbox
issue_org: sstok
issue_repo_name: gush-experiments-sandbox
